seed: 42
device: auto

data:
  image_size: 128

model:
  num_classes: 2
  base_ch: 64
  time_dim: 256

diffusion:
  timesteps: 10000
  schedule: cosine

checkpoint:
  path: /users/PCS0229/imankhazrak/Pink_Eye/outputs/ddpm_v2/checkpoints/ddpm_epoch1024.pt
  state_key: ema_state_dict

sample:
  num_per_class: 1000
  batch_size: 16

output:
  dir: /users/PCS0229/imankhazrak/Pink_Eye/outputs/ddpm_v2/generated_1000_per_class_epoch1024
